name: sleep_cycle_estimator
version: 0.0.1
description: An Angular 2 and Polymer Dart application for estimating optimal bedtimes.

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  angular2: 2.0.0-beta.0
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.5
  polymer: ^1.0.0-rc.7
  reflectable: ^0.3.1
  web_components: ^0.12.0
  logging: any
  intl: any

transformers:
- angular2:
    entry_points: web/main.dart
- web_components:
    entry_points: web/index.html
- reflectable:
    entry_points: web/index.bootstrap.initialize.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
